### ISSUE TITLE
Are the cropped cats and dogs datasets available?

### ISSUE THREAD

**Issue by lyhangustc** [mingyuliutw/UNIT#27]
I am so interested in the _Dog Breed Image Translation_ and the _Cat Species Image Translation_. Are the cropped cats and dogs datasets used in the experiments available?

**Comment by mingyuliutw** [comment]
The cropped images are from the ImageNet dataset. I am not sure if I am legally allowed to redistribute the cropped images from the ImageNet dataset.

I have consulted our company lawyer. I do not have the right to distribute the datasets.

**Comment by lyhangustc** [comment]
Thanks for your reply.

Can you describe more details about these datasets so that I can redo the experiments myself?
Like:
* Which template matching algorithm do you use to detect the head regions of cats and dogs? It seems only cat/dog heads with frontal poses are selected.
* How many images are there in each training dataset?
* Do you mix all breeds of cats (Egyptian cats, Persian cats and etc.) under the subset of _cat_ in the ImageNet together as _cat dataset_, or use only one of cat breeds as _cat datset_?
Also, have you tried UNIT on the whole cats and dogs (including heads, bodies, legs, and tails) instead of head regions only?

**Comment by mingyuliutw** [comment]
Sure.

- Template matching

I used VGG conv5 features for template matching. For each dog breed or cat specie, I manually cut 10-15 head portraits from the training set. They were my templates. I then performed multi-scale template matching, searching for the best candidate portrait (with most similar VGG conv5 feature) in each image. These matchers are then clustered into 100 clusters using their VGG conv5 features. We manually remove some clusters that contain no portraits. We also perform a similar step within each cluster.

- number of images

Each category contains 1-10K unique images.

- Mixed breed

Yes. I mixed Egyptian cats, Persian cats, Tiger cats, and Tabby cats. I didn't try to translate the entire image since I wanted to get high resolution outputs for the animal face regions.
